Mark docs template description as required
In my testing, attempts to create a docs site with no description would
fail with the error:

```
Unable to create file 'component-info.yaml'
Error message: 'collections.OrderedDict object' has no attribute 'description'
```

Better to mark it required than let the user hit the error.