address TypeScript compilation failure
This fixes...

```
Run yarn tsc
yarn run v1.22.1
$ tsc
plugins/splunk-on-call/src/components/EntitySplunkOnCallCard.test.tsx:158:26 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'Matcher'.
  Type 'undefined' is not assignable to type 'Matcher'.

158         expect(getByText(MOCK_INCIDENT.entityDisplayName)).toBeInTheDocument(),
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Mike Ball <mikedball@gmail.com>